/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FudbalRouteImport } from './routes/fudbal'
import { Route as KosarkaRouteImport } from './routes/kosarka'
import { Route as ONamaRouteImport } from './routes/o-nama'
import { Route as OstaliSportoviRouteImport } from './routes/ostali-sportovi'
import { Route as ClanakSlugRouteImport } from './routes/clanak.$slug'
import { Route as ApiPublicSlikeSplatRouteImport } from './routes/api/public/slike.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FudbalRoute = FudbalRouteImport.update({
  id: '/fudbal',
  path: '/fudbal',
  getParentRoute: () => rootRouteImport,
} as any)
const KosarkaRoute = KosarkaRouteImport.update({
  id: '/kosarka',
  path: '/kosarka',
  getParentRoute: () => rootRouteImport,
} as any)
const ONamaRoute = ONamaRouteImport.update({
  id: '/o-nama',
  path: '/o-nama',
  getParentRoute: () => rootRouteImport,
} as any)
const OstaliSportoviRoute = OstaliSportoviRouteImport.update({
  id: '/ostali-sportovi',
  path: '/ostali-sportovi',
  getParentRoute: () => rootRouteImport,
} as any)
const ClanakSlugRoute = ClanakSlugRouteImport.update({
  id: '/clanak/$slug',
  path: '/clanak/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSlikeSplatRoute = ApiPublicSlikeSplatRouteImport.update({
  id: '/api/public/slike/$',
  path: '/api/public/slike/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fudbal': typeof FudbalRoute
  '/kosarka': typeof KosarkaRoute
  '/o-nama': typeof ONamaRoute
  '/ostali-sportovi': typeof OstaliSportoviRoute
  '/clanak/$slug': typeof ClanakSlugRoute
  '/api/public/slike/$': typeof ApiPublicSlikeSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fudbal': typeof FudbalRoute
  '/kosarka': typeof KosarkaRoute
  '/o-nama': typeof ONamaRoute
  '/ostali-sportovi': typeof OstaliSportoviRoute
  '/clanak/$slug': typeof ClanakSlugRoute
  '/api/public/slike/$': typeof ApiPublicSlikeSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fudbal': typeof FudbalRoute
  '/kosarka': typeof KosarkaRoute
  '/o-nama': typeof ONamaRoute
  '/ostali-sportovi': typeof OstaliSportoviRoute
  '/clanak/$slug': typeof ClanakSlugRoute
  '/api/public/slike/$': typeof ApiPublicSlikeSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fudbal'
    | '/kosarka'
    | '/o-nama'
    | '/ostali-sportovi'
    | '/clanak/$slug'
    | '/api/public/slike/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fudbal'
    | '/kosarka'
    | '/o-nama'
    | '/ostali-sportovi'
    | '/clanak/$slug'
    | '/api/public/slike/$'
  id:
    | '__root__'
    | '/'
    | '/fudbal'
    | '/kosarka'
    | '/o-nama'
    | '/ostali-sportovi'
    | '/clanak/$slug'
    | '/api/public/slike/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FudbalRoute: typeof FudbalRoute
  KosarkaRoute: typeof KosarkaRoute
  ONamaRoute: typeof ONamaRoute
  OstaliSportoviRoute: typeof OstaliSportoviRoute
  ClanakSlugRoute: typeof ClanakSlugRoute
  ApiPublicSlikeSplatRoute: typeof ApiPublicSlikeSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fudbal': {
      id: '/fudbal'
      path: '/fudbal'
      fullPath: '/fudbal'
      preLoaderRoute: typeof FudbalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kosarka': {
      id: '/kosarka'
      path: '/kosarka'
      fullPath: '/kosarka'
      preLoaderRoute: typeof KosarkaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-nama': {
      id: '/o-nama'
      path: '/o-nama'
      fullPath: '/o-nama'
      preLoaderRoute: typeof ONamaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ostali-sportovi': {
      id: '/ostali-sportovi'
      path: '/ostali-sportovi'
      fullPath: '/ostali-sportovi'
      preLoaderRoute: typeof OstaliSportoviRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clanak/$slug': {
      id: '/clanak/$slug'
      path: '/clanak/$slug'
      fullPath: '/clanak/$slug'
      preLoaderRoute: typeof ClanakSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/slike/$': {
      id: '/api/public/slike/$'
      path: '/api/public/slike/$'
      fullPath: '/api/public/slike/$'
      preLoaderRoute: typeof ApiPublicSlikeSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FudbalRoute: FudbalRoute,
  KosarkaRoute: KosarkaRoute,
  ONamaRoute: ONamaRoute,
  OstaliSportoviRoute: OstaliSportoviRoute,
  ClanakSlugRoute: ClanakSlugRoute,
  ApiPublicSlikeSplatRoute: ApiPublicSlikeSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
